package consulkv

import (
	"sync"

	"github.com/coredns/coredns/plugin"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	successfulQueries = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: plugin.Namespace,
		Subsystem: "consulkv",
		Name:      "successful_queries_total",
		Help:      "Count of successful DNS queries handled by the ConsulKV plugin.",
	}, []string{"zone", "type"})

	failedQueries = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: plugin.Namespace,
		Subsystem: "consulkv",
		Name:      "failed_queries_total",
		Help:      "Count of failed DNS queries handled by the ConsulKV plugin.",
	}, []string{"zone"})

	consulErrors = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: plugin.Namespace,
		Subsystem: "consulkv",
		Name:      "consul_errors_total",
		Help:      "Count of errors when connecting to or querying Consul.",
	}, []string{"zone"})

	invalidResponses = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: plugin.Namespace,
		Subsystem: "consulkv",
		Name:      "invalid_responses_total",
		Help:      "Count of invalid DNS responses generated by the ConsulKV plugin.",
	}, []string{"zone", "type"})
)

var _ sync.Once
